In [1]:
import pandas as pd

In [30]:
dataset = pd.read_csv(r"C:\Users\hp\Desktop\NLP\sentiment_analysis.csv")
dataset.head(3)

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook

In [31]:
dataset.drop(columns = ["Year", "Month", "Day"], inplace =  True, axis = 1)

In [32]:
dataset

,Time of Tweet,text,sentiment,Platform
0,morning,What a great day!!! Looks like dream.,positive,Twitter
1,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,night,Don't angry me,negative,Facebook
3,morning,We attend in the class just for listening teac...,negative,Facebook
4,noon,"Those who want to go, let them go",negative,Instagram
...,...,...,...,...
494,night,"According to , a quarter of families under six...",negative,Twitter
495,morning,the plan to not spend money is not going well,negative,Instagram
496,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook
497,night,congratulations ! you guys finish a month ear...,positive,Twitter
498,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram

In [33]:
# dataset["Time of Tweet"].nunique()
dataset["sentiment"].unique()
dataset["Platform"].unique()

array([' Twitter  ', ' Facebook ', 'Facebook', ' Instagram ', ' Twitter '],
      dtype=object)

In [34]:
def make_changes(platform):
    if platform == " Facebook ":
        return "Facebook"
    elif platform == " Twitter  ":
        return "Twitter"
    else:
        return platform
    # array([' Twitter  ', 'Facebook', ' Instagram ', 'Twitter'], dtype=object)

In [35]:
dataset["Platform"] = dataset["Platform"].apply(make_changes)

In [36]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Time of Tweet  499 non-null    object
 1   text           499 non-null    object
 2   sentiment      499 non-null    object
 3   Platform       499 non-null    object
dtypes: object(4)
memory usage: 15.7+ KB

In [37]:
cat = ["Time of Tweet", "Platform"]

In [38]:
X = dataset.drop("sentiment", axis = 1)
y = dataset["sentiment"]

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
# cat
# ohe = OneHotEncoder(drop = "first")

# for col in cat:
    # X_train[col] =  ohe.fit_transform(X_train[col], X_test[col])

preprocessor = ColumnTransformer(transformers = [("ohe", OneHotEncoder(handle_unknown = "ignore"), cat),
                                                ("scaler", StandardScaler(), )])

preprocessor.fit(X_train)
X_train =  preprocessor.transform(X_train)
X_test = preprocessor.transform(X_test)

ValueError: not enough values to unpack (expected 3, got 1)

In [26]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 798 stored elements and shape (399, 7)>

['ohe__Time of Tweet_morning' 'ohe__Time of Tweet_night'
 'ohe__Time of Tweet_noon' 'ohe__Platform_ Instagram '
 'ohe__Platform_ Twitter ' 'ohe__Platform_Facebook'
 'ohe__Platform_Twitter']